.github/workflows/build.yml, configure, extlib/src/SDL_mixer-1.2.12/Makefile.in
..plus a few minor fixes discovered while creating this.
Currently the CI job is only for `ubuntu-latest` (`jammy` as of this writing), `macosx` jobs will require the addition of support for the Clang compiler suite.
=> add a CI workflow for GitHub

configure
In Linux, this basically marks the binary with a run path of the full path of `extlib/lib/` in the directory the source code was unpacked to -- almost definitely something we do not want.
=> extlibs/SDL: disable rpath when using internal SDL

configure
I have modified the script to accept clang as a supported compiler. ONScripter-EN builds without fail using clang, this useful mostly on OpenBSD and FreeBSD. I've made it so any OS that also uses clang can be easily added in the future. I've also fixed the bzip2 check on OpenBSD, and as above I've made it so any other OS that uses different paths for bzip2 libraries and headers can be easily added to it. Lastly, I've changed the compiler optimisation flags from -O3 to -O2, as -O3 is generally not recommended.
=> configure: clang as a supported compiler, OpenBSD fixes, -O3 to -O2

configure
Minor fix. I've realised that the `case` is not needed, as the `-I` and `-L` can be simply passed to what was there already. This way this should also apply to any other operating system where bzip2 headers and libraries are stored in /usr/local/ without having to add it manually.
=> Minor fix for bzip2 check

ScriptHandler.cpp
Multibyte characters were not being properly checked against the clickstr. Fixed by moving the successful match logic to the end of the for loop.
=> Fix multibyte clickstr checks

ONScripterLabel.cpp
The default_font variable was previously completely ignored, even when no default font was found in any of the font paths. Added logic so that default_font is always used if the -f/--font arg was passed.
=> Prioritize -f/--font arg when passed

.github/workflows/build.yml, Makefile.onscripter
This fixes builds with the GNU Make jobserver (`make -j`) to ensure that extlibs is built before any of core ONScripter-EN.
=> build: ensure dependencies are built/available before some source files

DirPaths.cpp, Linux_messagebox.cpp, ScriptHandler.cpp
The issues in this set were all discovered by compiling on Linux using `gcc` with `-fstack-protector -D_FORTIFY_SOURCE=2`.
There are more fixes to come soon, but these are probably mergeable now.
=> a smaller portion of a larger set of hardening fixes

extlib/src/SDL_mixer-1.2.12/Makefile.in
These binaries are not necessary for proper function of ONScripter-EN.
=> extlib: SDL_mixer: do not build playwave or playmus

configure
This fixes the remaining linker issue for systems (such as OpenBSD) that do not put the X11 libraries in the default linker path.
=> configure: check for Xlib on POSIX-compliant operating systems

configure
Package automation tools usually expect this to "just work".
=> configure: install target should obey DESTDIR when it is set

configure
The test is not relevant for non-x86 platforms such as PowerPC.
=> configure: skip cpuid() test on non-x86 machines

.github/workflows/build.yml, .gitignore, tools/conv_shared.cpp, tools/libgnurx/Makefile
Adjusted the build.yml to run on both pushes to master, and PRs. It will build and upload the tools and the onscripter executable.
Currently builds and uploads for:
- Linux x86-64
- Windows MSYS2 mingw64 x86-64
- Windows MSYS2 mingw32 i686
Other platforms will have to come online as we make it possible to build them again. Currently MacOS is the biggest issue.
This also includes an fix for #52, but @SeanMcG should take a look and ensure it works for their branches. Happy to remove it from this PR if it or an alternate fix goes through, I just needed it for getting tools to build across the three platforms above.
=> CI for PRs and pushes to master

msys2/Makefile.Windows.MSYS2.x86-64.insani
When running the 64-bit build on Windows 7 you'll hit this:
The docs for the function illuminate the need to link usp10.lib for Windows prior to 10. Turns out the 32-bit build has had the fix this whole time, so I copy/pasted the line and it worked straight away.
=> Fixing the 64-bit build for Windows 7

msys2/Makefile.Windows.MSYS2.i686.insani, msys2/Makefile.Windows.MSYS2.x86-64.insani
Seems that mingw doesn't strip binaries by default. I kind of assumed this was already being done but @SeanMcG asked and after some testing it turns out it doesn't. A nearly 3.5MB win here in binary size..
=> Strip debug info from Windows builds.

Makefile.extlibs
zlib-1.2.3 does not include a `pkgconfig` script, so we have to force this here in order to not use the system libraries.
=> extlibs/png: ensure to use the internal copy of zlib

.github/workflows/build.yml, .gitignore, .gitmodules, Makefile.extlibs, Makefile.unittest, configure, msys2/Makefile.Windows.MSYS2.i686.insani, msys2/Makefile.Windows.MSYS2.x86-64.insani, test/Makefile, test/Makefile.testlibs, test/test_Encoding.cpp
For now, apart from adding a few tests for 'Encoding', this just sets up the 2 dependencies to be downloaded, checksummed, built and installed.
The tests can be run with `make check`.
Additionally, a code coverage report can be generated by building all targets with `COVERAGE=1` and running the tests, then feeding the result to `gcov`.
=> add some unit tests using GTest and GMock

Makefile.unittest
This was accidentally commented out in 368160c3eebf57ead2a4c49df6dbd3b382aa7140.
=> tests: do not build with coverage enabled by default

ScriptHandler.cpp
This fixes the issue where we don't pick up a `;gameid` command when there's an empty line before it and no mode before that.
=> Skip empty lines at the start and in between `;` commands.

tools/arcmake.cpp
=> tools/arcmake: do not call fclose() on a FILE * we do not own

extlib/src/libogg-1.3.5/src/bitwise.c, extlib/src/libogg-1.3.5/src/framing.c
Post-`1.3.5` patch here: https://gitlab.xiph.org/xiph/ogg/-/commit/7cf42ea17aef7bc1b7b21af70724840a96c2e7d0
=> extlib/libogg: apply upstream patch to fix undefined behaviour

.github/workflows/build.yml, BaseReader.h, DirectReader.cpp, Encoding.cpp, NsaReader.cpp, ONScripterLabel.cpp, ONScripterLabel.h, ONScripterLabel_command.cpp, ONScripterLabel_effect.cpp, ONScripterLabel_effect_breakup.cpp, ONScripterLabel_effect_trig.cpp, ONScripterLabel_event.cpp, ONScripterLabel_file.cpp, ONScripterLabel_sound.cpp, ONScripterLabel_text.cpp, ONScripterReporter.cpp, ScriptHandler.cpp, ScriptHandler.h, ScriptParser.h, ScriptParser_command.cpp, tools/arcmake.cpp, tools/conv_shared.cpp, tools/libgnurx/regex_internal.h
There's a ton of various warnings we have, this resolves _most_ of them, with the intent to introduce no functional changes. There's a few warnings I haven't addressed yet due to either being unsure how to fix it without introducing a functional change, or them only appearing on Linux/when building our deps. I'll work on those in another PR.
Some categories of issues along with a few select issues:
- Unused variable: These range from parameters that aren't used, because they're a base class impl, or a callback that doesn't need the parameters, to code that's been orphaned and is unclear if they're needed anymore, to code that's only used on some platforms, but are visible on all of them. Depending on the scenario, these were deleted, their names removed from function definitions, or …
=> Another Pass at fixing Warnings 

extlib/src/smpeg/MPEG.cpp, extlib/src/smpeg/MPEGaudio.h, extlib/src/smpeg/MPEGfilter.c, extlib/src/smpeg/MPEGsystem.cpp, extlib/src/smpeg/audio/MPEGaudio.cpp, extlib/src/smpeg/audio/filter.cpp, extlib/src/smpeg/audio/filter_2.cpp, extlib/src/smpeg/audio/mpeglayer1.cpp, extlib/src/smpeg/audio/mpeglayer2.cpp, extlib/src/smpeg/audio/mpeglayer3.cpp, extlib/src/smpeg/audio/mpegtoraw.cpp, extlib/src/smpeg/video/gdith.cpp, extlib/src/smpeg/video/jrevdct.cpp, extlib/src/smpeg/video/vhar128.cpp
It has always been intended as a hint to the compiler, however as of the ratification of the C++17 standard it is no longer permitted.
=> extlib/smpeg: remove the use of 'register' storage class specifier

test/Makefile
`BaseReader.h` is indirectly tracked via the make rules for the C++ files that #include it.
=> tests: BaseReader.h is not a direct dependency of the test

ONScripterLabel_command.cpp, ScriptHandler.cpp, ScriptHandler.h
In UTF-8 mode,
`getStringFromInteger` seems to behave differently than expected when used with `UTF-8`. It only displays `@@` regardless of whether the `prnum_info[no]->param` has the correct value.
I added a function, `convertNumToFullWidthStr()`, to convert numbers into full-width characters and replaced the `getStringFromInteger()` function with it. This works.
`getStringFromInteger()` 
However, it still exhibits the same issue as #83 overlapping text.
Once issue #84 is resolved, the overlapping text problem here will also be automatically fixed.
Since `convertNumToFullWidthStr()` only needs to work in UTF-8, it should be possible to merge it with `getStringFromInteger()`... (but I can't)
This has only been tested for a specific case: pscript.dat.
=> fix to show appropriate numbers by adding a function

Makefile.onscripter, configure
There's no need to specify this manually when the compiler can do it for us.
=> configure: allow the compiler to generate dependency data

test/test_DirectReader.cpp
Some implementations of strncpy() do not guarantee it.
=> test: ensure strings are correctly null-terminated

ONScripterLabel_text.cpp
In UTF-8 mode, 
Selective sentences are output in a form that is difficult to see.
I just annotated one line
`//info->newLine();`
And It works..
The function isEndOfLine() seems to be acting in a different way than intended in utf-8.
It has been tested only one specific case; pscript.dat
=> fix overlap csel dialogue (temp)

Makefile.extlibs, extlib/src/smpeg/audio/hufftable.cpp
The proper fix for a "narrowing conversion" warning/error it to be explicit about it using `static_cast`.
=> extlib/smpeg: hufftable narrowing conversion fix

DirectReader.cpp
It should be considered an error.
=> DirectReader: return NULL if the PathProvider cannot return an actual path
